### ISSUE TITLE
Colors are not the same

### ISSUE THREAD

**Issue by ahmedelgabri** [atelierbram/vim-colors_duotones#3]
First, thanks for this :blush: 

I was looking for Duotone dark for vim and found your repo, but I noticed that colors are not the same.

Here are the original [colors](https://github.com/simurai/duotone-dark-syntax/blob/master/styles/colors.less) when you compile them you get 

``` css
/* In order */
#eeebff;
#a391fd;
#6c6783;
#ffcc99;
#e49e58;
#7c756e;
#c4b8fe;
#2a2734;
#ffa852;
#413d51;
#454257;
#312e3d;
rgba(69, 66, 87, 0.26);
```

and these are the ones you are [using](https://github.com/atelierbram/vim-colors_duotones/blob/master/colors/duotone-dark.vim#L14-L30)

``` vim
" GUI color definitions
let s:gui00 = "2a2734"
let s:gui01 = "363442"
let s:gui02 = "545167"
let s:gui03 = "6c6783"
let s:gui04 = "7e75a9"
let s:gui05 = "9b87fd"
let s:gui06 = "c4b8fe"
let s:gui07 = "eeebff"
let s:gui08 = "6a51e6"
let s:gui09 = "e09142"
let s:gui0A = "ffa852"
let s:gui0B = "7c756e"
let s:gui0C = "ffcc99"
let s:gui0D = "ffba76"
let s:gui0E = "8b76f4"
let s:gui0F = "7a63ee"
```

**Comment by atelierbram** [comment]
Thanks for taking an interest in this.

> I noticed that colors are not the same

Are you familiar with Base16? Hence the 16 color values, for which the main ones _are the same_ though. The additional values give some flexibility, for example used here in Vim to handle the background-color for the gutter in split windows. 

Also it should be noted that with these conversions I try to get to _the essence_ of DuoTone themes, make color-schemes "_in the spirit of_" or "_based on_" DuoTone Themes; straight imitation is not what I'm after.

To take this to it's logical conclusion I started a new series of repos under the umbrella of  [Base2Tone](https://github.com/atelierbram/Base2Tone) with no less then 32 color-values. So there will be a Base2Tone-vim repo later in the year, which will be basically the same as this one, but with additional light color-schemes. Hopefully the new name will also help avoid confusion. 

All of this in the hope you will understand that I'm trying to strike a balance here: on the one hand I want to give credit to Simurai, and/but also not "steal his thunder", because this is going to be taken in a different direction with all of the conversions (TODO) and additional color-schemes.

Hope this answers your question. If there is any issue with the syntax highlighting in Vim specific with this color-scheme(s) please let me know.

**Comment by ahmedelgabri** [comment]
This makes it clear, I was actually looking for the exact same color-scheme but ported to vim. Maybe I'll do it myself then, but I will keep an eye on the Base2Tone project too. Thanks

**Comment by atelierbram** [comment]
You're welcome

> I was actually looking for the exact same color-scheme but ported to vim

Have you done a side by side comparison with Atom and Vim in the default dark scheme? Very close IMO. 

I am actually interested which part of the color-scheme puts you off _specifically_, but for that I need to know more; can't comment on generalizations. Anyway, thanks for the feedback.

**Comment by ahmedelgabri** [comment]
Here is a comparison left is Atom right is neovim inside tmux _(both with true color enabled)_, it is close indeed but I prefer the left version more to be honest. When it comes to colorschemes, it's very hard to be really logical and point exactly what _puts me off_ at the end of the day we see colors differently.

But simply put I feel like the right version is more _busy_ when I compare it to the left version.

<img width="1680" alt="screen shot 2016-03-31 at 21 10 36" src="https://cloud.githubusercontent.com/assets/63876/14187808/16e94e70-f785-11e5-9c22-ad05ac449c77.png">

**Comment by atelierbram** [comment]
So for the next version with Base2Tone I will have a good look at javascript syntax highlighting. But this also reminds me I really should put a disclaimer in place in the README, because the color schemes have been tested in the GUI version of Vim, and not the terminal version; am surprised it works at all with NeoVim in Tmux! Thanks for this, it's helpful.

**Comment by ahmedelgabri** [comment]
neovim with 24-bit (true) color support is nearly the same as the GUI now, because I have access to the whole spectrum of colors not just 16/256. And actually they removed `gui_running` from neovim https://github.com/neovim/neovim/pull/4155 so now whatever works with the GUI version _most probably_ will run on neovim just fine.

**Comment by atelierbram** [comment]
OK, then it probably is javascript specific, will see if I can hook into those syntax names and add on to the template, when finding the time for this.

**Comment by atelierbram** [comment]
Some javaScript specific issues are being fixed with the continuation of this repo at [Base2Tone-vim](https://github.com/atelierbram/Base2Tone-vim). For that I also used the [Enhanced JavaScript Syntax for Vim](https://github.com/jelera/vim-javascript-syntax) plugin, (recommended) which helps it along quite a bit, although there are still some tags which can't be targeted, because they don't exist. Also comes with separate light versions of the colorschemes BTW.

![Base2Tone Evening Dark](http://base2t.one/assets/img/png/Base2Tone-Evening-dark-vim_940x640.png) 
Base2Tone-Evening-dark

**Comment by ahmedelgabri** [comment]
Thanks for the update, will try to have a look at it in the coming weeks
